# Generated by Django 5.1.3 on 2024-11-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_on',
            new_name='enrolled_at',
        ),
    ]
