# Generated by Django 5.1.3 on 2024-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_created_at_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
